version: "3.9"
   
services:
    # SERVICE APP (NODE JS)
    node-app:
        build: .
        ports: 
            - 3000:3000
        environment:
            - PORT=3000
            
    # MONGO CONTAINER
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: tary
            MONGO_INITDB_ROOT_PASSWORD: youyou
        volumes: 
            - mongo-db:/data/db

volumes: 
    mongo-db:
  